# Generated by Django 4.0.10 on 2025-04-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_complited_forms_created_forms_users_delete_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='created_forms',
            old_name='creator',
            new_name='owner',
        ),
    ]
