# Generated by Django 4.0.10 on 2025-04-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_complited_forms_respondent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complited_forms',
            name='form',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='forms.created_forms'),
        ),
    ]
